-- 4a Listar los datos de los turnos de las personas que se atendieron para las especialidades que
--    comienzan con “Odon” en el año 2015
SELECT
	T.*
FROM
	TURNOS AS T
	INNER JOIN ESPECIALIDADES AS E ON T.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
WHERE
	EXTRACT(
		YEAR
		FROM
			T.FECHA_TURNO
	) = 2015
	AND E.DESCRIPCION_ESPECIALIDAD LIKE 'Odon%'
	-- 4b Listar la cantidad de turnos dados por año, y especialidad
SELECT
	EXTRACT(
		YEAR
		FROM
			T.FECHA_TURNO
	),
	E.DESCRIPCION_ESPECIALIDAD,
	COUNT(T.NUMERO_TURNO)
FROM
	TURNOS AS T
	INNER JOIN ESPECIALIDADES AS E ON T.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
GROUP BY
	EXTRACT(
		YEAR
		FROM
			T.FECHA_TURNO
	),
	E.DESCRIPCION_ESPECIALIDAD
ORDER BY
	EXTRACT(
		YEAR
		FROM
			T.FECHA_TURNO
	),
	E.DESCRIPCION_ESPECIALIDAD
	-- 4c Armar una vista que muestre la información para el año 2014 (ESPECIALIDAD,
	--    GENERO_SEXUAL, CANTIDAD_TURNOS) Ordenada por especialidad, y género sexual.
CREATE VIEW VW_RODRIGUEZ_DIAZ_MARTIN_EJERCICIO4C_VISTACANTIDADTURNOSEPSECIALIDADGENERO2014 AS
SELECT
	E.DESCRIPCION_ESPECIALIDAD,
	GS.GENERO_SEXUAL,
	COUNT(T.NUMERO_TURNO)
FROM
	TURNOS AS T
	INNER JOIN ESPECIALIDADES AS E ON T.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN PERSONAS AS P ON T.DNI_PERSONA = P.DNI_PERSONA
	INNER JOIN GENEROS_SEXUALES AS GS ON P.GENERO_PERSONA = GS.GENERO_SEXUAL
WHERE
	EXTRACT(
		YEAR
		FROM
			T.FECHA_TURNO
	) = 2014
GROUP BY
	E.DESCRIPCION_ESPECIALIDAD,
	GS.GENERO_SEXUAL
ORDER BY
	E.DESCRIPCION_ESPECIALIDAD,
	GS.GENERO_SEXUAL