-- 4 Listar las personas que se atendieron los dias martes y viernes, con profesionales y especializados en pediatria
SELECT
	PER.NOMBRE_PERSONA,
	PER.APELLIDO_PERSONA
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = T.CODIGO_ESPECIALIDAD
	INNER JOIN PERSONAS AS PER ON T.DNI_PERSONA = PER.DNI_PERSONA
	INNER JOIN DIAS_SEMANALES AS DS ON T.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	INNER JOIN HORARIOS AS H ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	AND H.HORA_DESDE = T.HORA_DESDE
	AND H.CODIGO_DIA_SEMANA = T.CODIGO_DIA_SEMANA
	AND H.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
WHERE
	E.DESCRIPCION_ESPECIALIDAD = 'Pediatria'
	AND DS.DIA_SEMANA = 'Martes'
UNION
SELECT
	PER.NOMBRE_PERSONA,
	PER.APELLIDO_PERSONA
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = T.CODIGO_ESPECIALIDAD
	INNER JOIN PERSONAS AS PER ON T.DNI_PERSONA = PER.DNI_PERSONA
	INNER JOIN DIAS_SEMANALES AS DS ON T.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	INNER JOIN HORARIOS AS H ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	AND H.HORA_DESDE = T.HORA_DESDE
	AND H.CODIGO_DIA_SEMANA = T.CODIGO_DIA_SEMANA
	AND H.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
WHERE
	E.DESCRIPCION_ESPECIALIDAD = 'Pediatria'
	AND DS.DIA_SEMANA = 'Viernes'
SELECT
	DISTINCT PER.NOMBRE_PERSONA,
	PER.APELLIDO_PERSONA
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = T.CODIGO_ESPECIALIDAD
	INNER JOIN PERSONAS AS PER ON T.DNI_PERSONA = PER.DNI_PERSONA
	INNER JOIN DIAS_SEMANALES AS DS ON T.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	INNER JOIN HORARIOS AS H ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	AND H.HORA_DESDE = T.HORA_DESDE
	AND H.CODIGO_DIA_SEMANA = T.CODIGO_DIA_SEMANA
	AND H.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
WHERE
	E.DESCRIPCION_ESPECIALIDAD = 'Pediatria'
	AND (
		DS.DIA_SEMANA = 'Martes'
		OR DS.DIA_SEMANA = 'Viernes'
	) -- b listar la cantidad de turnos efectuados por especialidad y por mes
SELECT
	TO_CHAR(T.FECHA_TURNO, 'YYYY-MM') AS FECHA,
	COUNT(NUMERO_TURNO)
FROM
	TURNOS AS T
	INNER JOIN PROFESIONALES AS P ON T.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	AND T.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
GROUP BY
	FECHA
ORDER BY
	FECHA