SELECT
	*
FROM
	PROFESIONALES
SELECT
	P.NOMBRE_PROFESIONAL,
	P.GENERO_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
SELECT
	*
FROM
	PERSONAS AS P
	INNER JOIN TURNOS AS T ON P.DNI_PERSONA = T.DNI_PERSONA
	-- b
SELECT
	*
FROM
	ESPECIALIDADES
	--c
SELECT
	*
FROM
	TURNOS AS T
	INNER JOIN PERSONAS AS P ON T.DNI_PERSONA = P.DNI_PERSONA
WHERE
	NUMERO_TURNO = 10
	--d Obtener los datos de los profesionales que tienen una especialidad específica (por ejemplo, con código 5).
SELECT
	PR.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES AS PR
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON PR.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
WHERE
	E.CODIGO_ESPECIALIDAD = 15
	--e Listar todos los días registrados en el esquema
SELECT
	*
FROM
	DIAS_SEMANALES
	--f Mostrar todos los horarios de un profesional específico en un día dado.
SELECT
	P.NOMBRE_PROFESIONAL,
	H.HORA_DESDE,
	H.DURACION,
	D.DIA_SEMANA
FROM
	HORARIOS AS H
	INNER JOIN PROFESIONALES AS P ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS D ON H.CODIGO_DIA_SEMANA = D.CODIGO_DIA_SEMANA
WHERE
	P.NOMBRE_PROFESIONAL = 'Roy'
	AND D.DIA_SEMANA = 'Lunes'
	--g Buscar los profesionales que tienen un horario que comienza a partir de las 10:00.
SELECT
	P.NOMBRE_PROFESIONAL,
	H.HORA_DESDE,
	H.DURACION,
	D.DIA_SEMANA
FROM
	HORARIOS AS H
	INNER JOIN PROFESIONALES AS P ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS D ON H.CODIGO_DIA_SEMANA = D.CODIGO_DIA_SEMANA
WHERE
	EXTRACT(
		HOUR
		FROM
			H.HORA_DESDE
	) > 10
	--h Obtener las especialidades que ha obtenido un profesional determinado.
SELECT
	*
FROM
	ESPECIALIDADES
SELECT
	P.NOMBRE_PROFESIONAL,
	PE.FECHA_OBTENCION_TITULO,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES P
	INNER JOIN PROFESIONALES_ESPECIALIDADES PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
WHERE
	P.NOMBRE_PROFESIONAL = 'Roy'
	--i Listar los días en los que trabaja un profesional específico.
SELECT DISTINCT
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA
FROM
	PROFESIONALES AS P
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
WHERE
	P.NOMBRE_PROFESIONAL = 'Roy'
	--j Mostrar todos los turnos asignados en una fecha concreta.
SELECT
	PR.NOMBRE_PROFESIONAL,
	PR.APELLIDO_PROFESIONAL,
	P.NOMBRE_PERSONA,
	P.APELLIDO_PERSONA,
	T.FECHA_TURNO
FROM
	TURNOS AS T
	INNER JOIN PERSONAS AS P ON T.DNI_PERSONA = P.DNI_PERSONA
	INNER JOIN PROFESIONALES AS PR ON PR.DNI_PROFESIONAL = T.DNI_PROFESIONAL
WHERE
	FECHA_TURNO = '2005-06-18'
	--k Crear una vista que liste los profesionales junto con sus especialidades.
CREATE OR REPLACE VIEW PROFESIONALES_Y_ESPECIALIDADES AS
SELECT
	P.NOMBRE_PROFESIONAL,
	PE.FECHA_OBTENCION_TITULO,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES P
	INNER JOIN PROFESIONALES_ESPECIALIDADES PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
SELECT
	*
FROM
	PROFESIONALES_Y_ESPECIALIDADES
	--l Mostrar los horarios de todos los profesionales en un día y horario específicos.
SELECT
	PR.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA,
	H.HORA_DESDE
FROM
	HORARIOS AS H
	INNER JOIN PROFESIONALES AS PR ON H.DNI_PROFESIONAL = PR.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
WHERE
	DS.DIA_SEMANA = 'Lunes'
	AND EXTRACT(
		HOUR
		FROM
			H.HORA_DESDE
	) > 10
	AND EXTRACT(
		HOUR
		FROM
			H.HORA_DESDE
	) < 20
	--m  Listar los profesionales que trabajan en más de un día en la semana.
SELECT
	P.NOMBRE_PROFESIONAL,
	COUNT(DISTINCT DS.DIA_SEMANA) AS DIAS_TRABAJADOS
FROM
	PROFESIONALES AS P
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
GROUP BY
	P.NOMBRE_PROFESIONAL
HAVING
	COUNT(DS.DIA_SEMANA) > 1
	--n Encontrar los profesionales que no tienen horario registrado.
SELECT
	*
FROM
	PROFESIONALES AS PR
	LEFT JOIN HORARIOS AS H ON PR.DNI_PROFESIONAL = H.DNI_PROFESIONAL
WHERE
	H.DNI_PROFESIONAL IS NULL
	--o Mostrar los profesionales con más de una disponibilidad en un mismo día.
SELECT
	PR.NOMBRE_PROFESIONAL,
	COUNT(H.HORA_DESDE) AS CANTIDAD_TURNOS_DISP,
	DS.DIA_SEMANA
FROM
	PROFESIONALES AS PR
	INNER JOIN HORARIOS AS H ON PR.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	LEFT JOIN TURNOS AS T ON H.HORA_DESDE = T.HORA_DESDE
	AND H.CODIGO_ESPECIALIDAD = T.CODIGO_ESPECIALIDAD
	AND H.CODIGO_DIA_SEMANA = T.CODIGO_DIA_SEMANA
	AND H.HORA_DESDE = T.HORA_DESDE
WHERE
	T.NUMERO_TURNO IS NULL
GROUP BY
	PR.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA
HAVING
	COUNT(H.HORA_DESDE) > 1
SELECT
	PR.NOMBRE_PROFESIONAL,
	COUNT(H.HORA_DESDE) AS CANTIDAD_TURNOS_DISP,
	DS.DIA_SEMANA
FROM
	PROFESIONALES AS PR
	INNER JOIN HORARIOS AS H ON PR.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
GROUP BY
	PR.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA
HAVING
	COUNT(H.HORA_DESDE) > 1
	--p Buscar las personas que trabajan en un turno y también están registradas como profesionales.
	--q. Obtener una lista de todos los días en los que hay turnos asignados para un profesional determinado.
SELECT DISTINCT
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA
FROM
	PROFESIONALES AS P
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON T.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
WHERE
	P.NOMBRE_PROFESIONAL = 'Roberta'
	--r Listar las especialidades que tiene cada profesional, agrupadas por profesional.
SELECT
	P.NOMBRE_PROFESIONAL,
	COUNT(E.DESCRIPCION_ESPECIALIDAD)
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
GROUP BY
	P.NOMBRE_PROFESIONAL
SELECT
	P.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
GROUP BY
	E.DESCRIPCION_ESPECIALIDAD,
	P.NOMBRE_PROFESIONAL
SELECT
	*
FROM
	ESPECIALIDADES
	-- s Crear un reporte con los profesionales, las especialidades y los días quetrabajan en una consulta.
SELECT
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA,
	E.DESCRIPCION_ESPECIALIDAD
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN PROFESIONALES_ESPECIALIDADES_DIAS_SEMANALES AS PES ON P.DNI_PROFESIONAL = PES.DNI_PROFESIONAL
	AND E.CODIGO_ESPECIALIDAD = PES.CODIGO_ESPECIALIDAD
	INNER JOIN DIAS_SEMANALES AS DS ON PES.CODIGO_DIA_SEMANA = PES.CODIGO_DIA_SEMANA
ORDER BY
	P.NOMBRE_PROFESIONAL,
	DS.CODIGO_DIA_SEMANA
	-- t Mostrar los horarios en los que trabajan los profesionales, en orden cronológico
SELECT
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA,
	H.HORA_DESDE
FROM
	PROFESIONALES AS P
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
ORDER BY
	P.NOMBRE_PROFESIONAL,
	DS.CODIGO_DIA_SEMANA,
	H.HORA_DESDE
	-- u Localizar los profesionales que trabajan en un día y hora específicos y tienen más de una especialidad.
SELECT
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA,
	H.HORA_DESDE
FROM
	PROFESIONALES AS P
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
WHERE
	DS.DIA_SEMANA = 'Lunes'
GROUP BY
	P.NOMBRE_PROFESIONAL,
	DS.DIA_SEMANA,
	H.HORA_DESDE,
	DS.CODIGO_DIA_SEMANA
HAVING
	COUNT(PE.CODIGO_ESPECIALIDAD) > 1
ORDER BY
	P.NOMBRE_PROFESIONAL,
	DS.CODIGO_DIA_SEMANA,
	H.HORA_DESDE
	-- v Mostrar los profesionales que no trabajan en un día determinado.
SELECT
	*
FROM
	PROFESIONALES AS P
	LEFT JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	AND H.CODIGO_DIA_SEMANA = 1
WHERE
	H.DNI_PROFESIONAL IS NULL
	-- w Encontrar los profesionales que trabajan siempre en diferentes días, pero en horarios similares.
SELECT
	P.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD,
	COUNT(DISTINCT DS.DIA_SEMANA) AS DIAS_CON_HORARIO_SIMILAR
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
WHERE
	EXTRACT(
		HOUR
		FROM
			H.HORA_DESDE
	) BETWEEN 10 AND 11
GROUP BY
	P.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD
HAVING
	COUNT(DISTINCT DS.DIA_SEMANA) > 1
	-- x Generar una vista que relacione profesionales, días, horarios y turnos.
CREATE VIEW TURNOS_DIA_HORARIO AS
SELECT
	P.NOMBRE_PROFESIONAL,
	P.APELLIDO_PROFESIONAL,
	T.FECHA_TURNO,
	DS.DIA_SEMANA,
	H.HORA_DESDE
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND H.HORA_DESDE = T.HORA_DESDE
	AND T.CODIGO_DIA_SEMANA = H.CODIGO_DIA_SEMANA
	AND T.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	-- y Obtener los profesionales y sus horarios, solo para las especialidades que comienzan con la letra 'A'.
SELECT
	P.NOMBRE_PROFESIONAL,
	P.APELLIDO_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD,
	H.HORA_DESDE
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	AND H.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
WHERE
	E.DESCRIPCION_ESPECIALIDAD LIKE 'A%'
	-- z Buscar los profesionales que tienen más de 3 turnos asignados en una semana.
SELECT
	P.NOMBRE_PROFESIONAL,
	DATE_PART('year', T.FECHA_TURNO::DATE) AS ANIO,
	DATE_PART('week', T.FECHA_TURNO::DATE) AS SEMANA,
	COUNT(T.NUMERO_TURNO)
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = T.CODIGO_ESPECIALIDAD
GROUP BY
	DATE_PART('year', T.FECHA_TURNO::DATE),
	DATE_PART('week', T.FECHA_TURNO::DATE),
	P.NOMBRE_PROFESIONAL
HAVING
	COUNT(T.NUMERO_TURNO) > 1
ORDER BY
	ANIO,
	P.NOMBRE_PROFESIONAL
	-- aa Listar los profesionales que tienen duplicados en horarios en diferentes días.
SELECT DISTINCT
	P.NOMBRE_PROFESIONAL
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = H.CODIGO_ESPECIALIDAD
WHERE
	H.HORA_DESDE IN (
		SELECT
			H.HORA_DESDE
		FROM
			PROFESIONALES AS P
			INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
			INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
			AND PE.CODIGO_ESPECIALIDAD = H.CODIGO_ESPECIALIDAD
	)
SELECT
	H.HORA_DESDE
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN HORARIOS AS H ON P.DNI_PROFESIONAL = H.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = H.CODIGO_ESPECIALIDAD
	-- bb Crear una vista que agrupe los profesionales según el género de la persona registrada
	-- cc Consultar las especialidades y días en los que trabaja un profesional, usando subconsultas
SELECT
	P.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD,
	PES.CODIGO_DIA_SEMANA
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN PROFESIONALES_ESPECIALIDADES_DIAS_SEMANALES AS PES ON P.DNI_PROFESIONAL = PES.DNI_PROFESIONAL
	AND PE.CODIGO_ESPECIALIDAD = PES.CODIGO_ESPECIALIDAD
WHERE
	P.NOMBRE_PROFESIONAL = 'Roberta'
	-- dd . Realizar una consulta que combine varias tablas para listar todo el personal,
	-- las especialidades que poseen, los horarios y los turnos asignados en una sola consulta.
SELECT
	P.NOMBRE_PROFESIONAL,
	E.DESCRIPCION_ESPECIALIDAD,
	T.FECHA_TURNO,
	T.HORA_DESDE,
	DS.DIA_SEMANA
FROM
	PROFESIONALES AS P
	INNER JOIN PROFESIONALES_ESPECIALIDADES AS PE ON P.DNI_PROFESIONAL = PE.DNI_PROFESIONAL
	INNER JOIN ESPECIALIDADES AS E ON PE.CODIGO_ESPECIALIDAD = E.CODIGO_ESPECIALIDAD
	INNER JOIN HORARIOS AS H ON H.DNI_PROFESIONAL = P.DNI_PROFESIONAL
	AND H.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
	INNER JOIN DIAS_SEMANALES AS DS ON H.CODIGO_DIA_SEMANA = DS.CODIGO_DIA_SEMANA
	INNER JOIN TURNOS AS T ON P.DNI_PROFESIONAL = T.DNI_PROFESIONAL
	AND T.CODIGO_DIA_SEMANA = H.CODIGO_DIA_SEMANA
	AND T.CODIGO_ESPECIALIDAD = PE.CODIGO_ESPECIALIDAD
	AND H.HORA_DESDE = T.HORA_DESDE
ORDER BY
	T.FECHA_TURNO , DS.codigo_dia_semana

	-- CONSULTAR n, p, v, w, aa, bb